services:
  - type: web
    name: speedysign
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXPO_PUBLIC_SUPABASE_URL
        sync: false
      - key: EXPO_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: EXPO_PUBLIC_SIGNING_SERVER_URL
        sync: false
    dockerBuildArgs:
      - EXPO_PUBLIC_SUPABASE_URL
      - EXPO_PUBLIC_SUPABASE_ANON_KEY
      - EXPO_PUBLIC_SIGNING_SERVER_URL
